apiVersion: batch/v1
kind: Job
metadata:
  name: chaos-working-experiment
  namespace: default
  labels:
    app: chaos-toolkit-working
spec:
  template:
    metadata:
      labels:
        app: chaos-toolkit-working
    spec:
      serviceAccountName: chaos-runner
      containers:
      - name: chaos-toolkit
        image: python:3.9-slim
        command: ["/bin/sh"]
        args:
          - -c
          - |
            echo "🔥 Working Chaos Toolkit Experiment - SPEED FIXED!"
            echo "📁 Experiment file: /experiments/working-pod-chaos.json"
            
            # Install Chaos Toolkit and Kubernetes extension in one go
            pip install --no-cache-dir --quiet chaostoolkit chaostoolkit-kubernetes
            
            # Run the chaos experiment
            echo "🚀 Running Chaos Toolkit experiment..."
            chaos run /experiments/working-pod-chaos.json
            
            echo "✅ Chaos Toolkit experiment completed!"
        env:
        - name: KUBERNETES_SERVICE_HOST
          value: "kubernetes.default.svc"
        - name: KUBERNETES_SERVICE_PORT
          value: "443"
        - name: KUBERNETES_SERVICE_PORT_HTTPS
          value: "443"
        volumeMounts:
        - name: experiments
          mountPath: /experiments
        - name: kubeconfig
          mountPath: "/var/run/secrets/kubernetes.io/serviceaccount"
          readOnly: true
      volumes:
      - name: experiments
        configMap:
          name: chaos-experiments
      - name: kubeconfig
        secret:
          secretName: chaos-runner-token
      restartPolicy: Never
  backoffLimit: 3
