apiVersion: batch/v1
kind: Job
metadata:
  name: wait-for-constrainttemplate-crds
  namespace: gatekeeper-system
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "0.5"  # Runs after ConstraintTemplates (wave 0), before Constraints (wave 1)
spec:
  template:
    spec:
      serviceAccountName: default
      restartPolicy: OnFailure
      containers:
      - name: wait-for-crds
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          echo "Waiting for ConstraintTemplate CRDs to be established..."
          
          # List of ConstraintTemplate CRDs that need to be ready
          # These are created by Gatekeeper after ConstraintTemplates are applied
          CRDS=(
            "k8srequirednonroots.constraints.gatekeeper.sh"
            "k8srequiredresources.constraints.gatekeeper.sh"
            "k8sdisallowlatesttags.constraints.gatekeeper.sh"
            "k8srequiredreadonlyfs.constraints.gatekeeper.sh"
            "k8sdisallowprivilegeds.constraints.gatekeeper.sh"
            "k8srequiredlabels.constraints.gatekeeper.sh"
          )
          
          echo "Waiting for ConstraintTemplates to be processed by Gatekeeper..."
          echo "This hook runs after ConstraintTemplates (wave 0) are synced"
          sleep 10  # Give Gatekeeper time to process ConstraintTemplates
          
          # Wait for each CRD to be established
          ALL_READY=true
          for CRD in "${CRDS[@]}"; do
            echo "Waiting for CRD: $CRD"
            MAX_ATTEMPTS=30  # 30 attempts × 5 seconds = 2.5 minutes
            ATTEMPT=0
            CRD_READY=false
            
            while [ $ATTEMPT -lt $MAX_ATTEMPTS ]; do
              if kubectl get crd $CRD &>/dev/null; then
                if kubectl wait --for=condition=established crd/$CRD --timeout=5s &>/dev/null; then
                  echo "✅ CRD $CRD is ready!"
                  CRD_READY=true
                  break
                fi
              fi
              ATTEMPT=$((ATTEMPT + 1))
              if [ $((ATTEMPT % 6)) -eq 0 ]; then
                echo "⏳ Attempt $ATTEMPT/$MAX_ATTEMPTS: CRD $CRD not ready yet..."
              fi
              sleep 5
            done
            
            if [ "$CRD_READY" = "false" ]; then
              echo "❌ CRD $CRD not ready after $MAX_ATTEMPTS attempts"
              ALL_READY=false
            fi
          done
          
          if [ "$ALL_READY" = "false" ]; then
            echo "⚠️  Some CRDs are not ready, but continuing..."
            echo "Constraints may fail to sync. You may need to manually sync again."
          fi
          
          # Also wait for Gatekeeper controller to be ready (in case it's not)
          echo "Waiting for Gatekeeper controller to be ready..."
          kubectl wait --for=condition=ready \
            pod -l control-plane=controller-manager \
            -n gatekeeper-system \
            --timeout=60s || {
              echo "⚠️  Gatekeeper controller not ready, but continuing..."
            }
          
          echo "✅ ConstraintTemplate CRDs are ready!"
          sleep 3  # Give CRDs a moment to fully propagate

