apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chaos-toolkit-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:Lforlinux/k8s-platform-toolkit.git
    targetRevision: feature/k6-performance-testing
    path: argocd/apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  revisionHistoryLimit: 10

