apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sanity-test
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: sanity-test
    repoURL: https://github.com/Lforlinux/chaos-toolkit-k8s.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: sanity-test
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  revisionHistoryLimit: 10

