apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservices-demo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: application/online-boutique
    repoURL: git@github.com:Lforlinux/k8s-platform-toolkit.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: online-boutique
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  revisionHistoryLimit: 10
