apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opa-policies
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Lforlinux/k8s-platform-toolkit.git
    targetRevision: HEAD
    path: opa/k8s-policy-manifest
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: gatekeeper-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true  # Prune resources last (after all resources are synced)
      - RespectSyncWave=true  # Respect sync waves to ensure proper ordering
    automated:
      prune: true
      selfHeal: true
  revisionHistoryLimit: 10

