apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opa-constraints
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Lforlinux/k8s-platform-toolkit.git
    targetRevision: HEAD
    path: opa/k8s-policy-manifest/constraints-only
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: gatekeeper-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - RespectSyncWave=true
    automated:
      prune: true
      selfHeal: true
  revisionHistoryLimit: 10

